### ISSUE TITLE
Fix failing CI workflow

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/groovy-test-runner#4]
The [CI workflow fails](https://github.com/exercism/groovy-test-runner/actions/workflows/ci.yml), even though running `bin/run-tests-in-docker.sh` locally works fine. This should be fixed.

**Comment by angelikatyborska** [comment]
> even though running bin/run-tests-in-docker.sh locally works fine

Not for me. I get the same failures locally as on CI. I never installed Groovy locally so that might be a clue.

I observer the the gradle home directory (where the deps cache would be, right?) gets purged after every step, I tested that by adding:
```
RUN gradle build && ls -al /home/gradle/.gradle
RUN ls -al /home/gradle/.gradle
```

This might be related: https://fix.code-error.com/how-to-make-gradle-cache-persistent-through-docker-containers/

**Comment by angelikatyborska** [comment]
I tried multiple ways of changing's gradle home directory to preserve the cache, but each time I run into this issue that I have no idea how to resolve: https://github.com/gradle/gradle/issues/8107

I don't know if gradle home directory needs to be owned by root, or the gradle user, I tried both and it didn't change anything.

**Comment by angelikatyborska** [comment]
Ok, so I figured out that the problem is the docker run option `--read-only`, gradle just won't run on a read-only filesystem?

**Comment by angelikatyborska** [comment]
Ah, now I see that a similar discussion has been happening in Kotlin's test runner too

**Comment by ErikSchierboom** [comment]
Yeah, Gradle was acting weird when I looked into this. It's fine for now.
